[project]
name = "03-3-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dashscope>=1.23.4",
    "langchain-community>=0.3.24",
    "langgraph>=0.4.8",
]
